/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as EnhancementRouteImport } from './routes/enhancement'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ValidationRouteImport } from './routes/validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EnhancementRoute = EnhancementRouteImport.update({
  id: '/enhancement',
  path: '/enhancement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/enhancement': typeof EnhancementRoute
  '/results': typeof ResultsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/enhancement': typeof EnhancementRoute
  '/results': typeof ResultsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/enhancement': typeof EnhancementRoute
  '/results': typeof ResultsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/enhancement'
    | '/results'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/enhancement'
    | '/results'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/enhancement'
    | '/results'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  EnhancementRoute: typeof EnhancementRoute
  ResultsRoute: typeof ResultsRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enhancement': {
      id: '/enhancement'
      path: '/enhancement'
      fullPath: '/enhancement'
      preLoaderRoute: typeof EnhancementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  EnhancementRoute: EnhancementRoute,
  ResultsRoute: ResultsRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
